---
# CHOICE OF SERIALISATION FORMAT ===============================================
#
# This file has been specified in the yaml format because json doesn't allow
# comments. But the upload script also accepts json.
#
# SCHEMA (USERS) ===============================================================
#
# Users can be specified as follows:
#

users:
  - Adela Sobotkova
  - Brian Ballsun-Stanton
  - Faims Admin
  - Penny Crook

#
# The server provides a default list of users when the module is created. If a
# list of users isn't provided in this yaml file, the default list will remain
# unchanged.
#
# SCHEMA (PROJECT_MODULE) ======================================================
#
# Fields from the "Create module" or "Edit module" pages can be set using the
# "project_module:" key. For example, to create/edit a module named
# "Perachora-2020" with an SRID of 4242, you'd write:
#
#   project_module:
#     name: "Perachora-2020"
#     srid: "4242"
#
# The keys allowed in "project_module:" (e.g. "name", "srid", etc) simply come
# from the FAIMS server's HTML form, so to know the complete list of keys, you
# can inspect the source of the form in a web browser.
#
# If a module name isn't given, the upload script will attempt to use the name
# of the module's git repo. If that doesn't exist, the parent directory's name
# will be used instead.
#

project_module: {}
